<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>keml.io</groupId>
  <artifactId>keml.io</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <build>
    <sourceDirectory>src</sourceDirectory>
    <plugins>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.8.1</version>
        <configuration>
          <release>21</release>
        </configuration>
      </plugin>
    </plugins>
  </build>
  <dependencies>
	  <dependency>
    	<groupId>com.fasterxml.jackson.core</groupId>
    	<artifactId>jackson-databind</artifactId>
    	<version>2.17.0</version>
	  </dependency>
	  <dependency>
    	<groupId>org.json</groupId>
    	<artifactId>json</artifactId>
    	<version>20240303</version>
	</dependency>
	<dependency>
    	<groupId>com.fasterxml.jackson.dataformat</groupId>
    	<artifactId>jackson-dataformat-xml</artifactId>
    	<version>2.16.0</version>
	</dependency>
	<dependency>
    	<groupId>org.eclipse.emfcloud</groupId>
    	<artifactId>emfjson-jackson</artifactId>
    	<version>2.2.0</version>
	</dependency>
	<dependency>
   		<groupId>org.eclipse.emf</groupId>
    	<artifactId>org.eclipse.emf.ecore</artifactId>
    	<version>2.35.0</version>
  	</dependency>
  	<dependency>
    	<groupId>org.eclipse.emf</groupId>
    	<artifactId>org.eclipse.emf.ecore.xmi</artifactId>
    	<version>2.35.0</version>
  	</dependency>
	<dependency>
		<groupId>keml</groupId>
		<artifactId>keml</artifactId>
		<version>0.0.1-SNAPSHOT</version>
	</dependency>
  </dependencies>
</project>